# Base configuration for Faster R-CNN on Cityscapes
# Override values using experiment configs under config/experiments/

project_name: faster_rcnn_cityscapes
experiment_name: baseline

data:
  root: data/                        # Project root for data
  images_dir: data/images
  annotations_dir: data/gtFine
  num_workers: 4                    # DataLoader(read img, decode, resize, augment, convert to tensors batchwise) workers for parallel loading ~ no of CPU cores else GPU may starve for data
  pin_memory: true                  # Speeds up data loading on GPU; Speeds up transfer from CPU RAM → GPU VRAM.

model:
  num_classes: 9                     # 8 Cityscapes classes + background
  #pretrained_backbone: true
  #pretrained_weights_path: str = "weights/fasterrcnn_resnet50_fpn_coco-258fb6c6.pth"
  backbone_weights: "local" #load downloaded pretrained weights from local path instead of torchvision's model zoo
  local_weights_path: "weights/fasterrcnn_resnet50_fpn_coco.pth"
  load_backbone_only: false              # If true, only load weights for resnet, not for fpn. as in imagenet pretrained weights - similar to 'imagenet' 
  trainable_backbone_layers: 3       # How many ResNet layers to fine-tune (0-5) 0 - freeze all, 1 - fine-tune last layer, 2 - fine-tune last 2 layers 5 - fine-tune all
  #layer in resnest have 3 to 6 bottleneck blocks - each block has 3 conv layers, so 3 layers in resnet have (3 or 6)*3=9 to 18 conv layers
  min_size: 800                     # Shortest side of the image after resizing, retains aspect ratio
  max_size: 1333                    # Longest side of the image after resizing, retains aspect ratio


  # Official download URLs (for reference / wget scripts)
  # ImageNet backbone:
  #   https://download.pytorch.org/models/resnet50-0676ba61.pth
  # Faster R-CNN COCO (full model):
  #   https://download.pytorch.org/models/fasterrcnn_resnet50_fpn_coco-258fb6c6.pth
  # Faster R-CNN V2 COCO (stronger backbone):
  #   https://download.pytorch.org/models/fasterrcnn_resnet50_fpn_v2_coco-dd69338a.pth



training:
  epochs: 20
  batch_size: 2                      # Faster R-CNN is memory-heavy; keep small
  
  #------optimizer hyperparameters------
  optimizer: "sgd"                    # "sgd" | "adamw" | "adam"
  learning_rate: 0.005
  momentum: 0.9                      # Momentum for SGD optimizer wt = wt-1 + lr*momentum, momentum vt = bvt-1 + gt
  weight_decay: 0.0005        # wt = wt - lr*weight_decay*wt -- creates same effect as L2 regularization in SGD to prevent overfitting, so no need to add L2 regularization term in loss function
  
  #------learning rate scheduler hyperparameters------
  lr_scheduler: "step"                # "step" | "cosine" | "none"
  lr_step_size: 7                    # StepLR: decay every N epochs
  lr_gamma: 0.1            # StepLR: decay factor (new_lr = old_lr * gamma)-- after 7 epochs, lr = lr*0.1, after 7 epochs, lrnew = lr*0.1
  
  #------gradient clipping------
  grad_clip: null                    # Optional gradient clipping value, when grad norm exceeds this value, it is scaled down to prevent exploding gradients, all gradients will be scaled down by the same factor(grad norm/clip_value) to maintain their relative magnitudes
  
  device: cuda                       # "cuda" or "cpu"


#-----loss
# faster rcnn has 4 internal losses- rpn classification loss, rpn regression loss, roi head classification loss, roi head regression loss
#this section lets u swap: classification loss:  "cross entropy" | "focal loss" 
# box_regression loss: "smooth l1" | "l1" | "giou" | "diou" | "ciou"
loss:
  classification: "cross_entropy"     # "cross_entropy" | "focal_loss"
  box_regression: "smooth_l1"        # "smooth_l1" | "l1" | "giou" | "diou" | "ciou"

  #focal loss params (used when classification: focal_loss)
  focal_alpha: 0.25
  focal_gamma: 2.0

  #smooth l1 loss params (used when box_regression: smooth_l1)
  smooth_l1_beta: 1.0


#-------evaluation------
eval:
  iou_thresholds: [0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95]         # IoU thresholds for mAP calculation
  score_threshold: 0.05              # Minimum confidence score for a detection to be considered in evaluation
  max_detections: 100       # Max detections per image for evaluation


#-----checkpointing------
#checkpointing naming: {experiment_name}_epoch{N:04d}_loss_{loss:.4f}_mAP{map50:.4f}.pth

checkpointing:
  save_dir: outputs/checkpoints/  
  save_every: 2                      # Save checkpoint every N epochs
  keep_last: 3                       # How many checkpoints to retain

#--- logging ----------
logging:
  tensorboard_dir: outputs/tensorboard/
  mlflow_tracking_uri: outputs/mlruns/
  log_every: 50                      # Log metrics every N batches

#-----profiler------
profiler:
  enabled: false
  wait: 1         # Number of epochs to wait before starting profiling (warmup)
  warmup: 1       # Number of epochs to perform warmup (profiling without recording results)
  active: 3       # Number of epochs to profile (record results)
  output_dir: outputs/profiler


#------------debug----
debug:
  enabled: false
  image_height: 600
  image_width: 800
  batch_size: 2